
ALTER TABLE nab.NabSpecimen ALTER COLUMN FitError TYPE DOUBLE PRECISION;
ALTER TABLE nab.NabSpecimen ALTER COLUMN AUC_poly TYPE DOUBLE PRECISION;
ALTER TABLE nab.NabSpecimen ALTER COLUMN PositiveAUC_Poly TYPE DOUBLE PRECISION;
ALTER TABLE nab.NabSpecimen ALTER COLUMN AUC_4pl TYPE DOUBLE PRECISION;
ALTER TABLE nab.NabSpecimen ALTER COLUMN PositiveAUC_4pl TYPE DOUBLE PRECISION;
ALTER TABLE nab.NabSpecimen ALTER COLUMN AUC_5pl TYPE DOUBLE PRECISION;
ALTER TABLE nab.NabSpecimen ALTER COLUMN PositiveAUC_5pl TYPE DOUBLE PRECISION;

ALTER TABLE nab.CutoffValue ALTER COLUMN Cutoff TYPE DOUBLE PRECISION;
ALTER TABLE nab.CutoffValue ALTER COLUMN Point TYPE DOUBLE PRECISION;
ALTER TABLE nab.CutoffValue ALTER COLUMN IC_Poly TYPE DOUBLE PRECISION;
ALTER TABLE nab.CutoffValue ALTER COLUMN IC_4pl TYPE DOUBLE PRECISION;
ALTER TABLE nab.CutoffValue ALTER COLUMN IC_5pl TYPE DOUBLE PRECISION;