package org.labkey.ms2.reader;

import org.labkey.api.search.AbstractDocumentParser;
import org.labkey.api.webdav.WebdavResource;
import org.xml.sax.ContentHandler;
import org.xml.sax.SAXException;

import java.io.IOException;
import java.io.InputStream;

/**
 * Mascot .dat file Lucene document parser
 * User: jeckels
 * Date: Feb 22, 2011
 */
public class DatDocumentParser extends AbstractDocumentParser
{
    @Override
    protected void parseContent(InputStream stream, ContentHandler handler) throws IOException, SAXException
    {
        // Intentionally no-op as the content isn't very interesting for full text search
    }

    public String getMediaType()
    {
        return "application/dat";
    }

    public boolean detect(WebdavResource resource, byte[] buf) throws IOException
    {
        if (resource.getName().endsWith(".dat") || getMediaType().equals(resource.getContentType()))
        {
            String header = new String(buf, 0, buf.length);
            return header.indexOf("Generated by Mascot") != -1;
        }
        return false;
    }
}
