
ALTER TABLE luminex.GuideSet ADD COLUMN ValueBased BOOLEAN;
UPDATE luminex.GuideSet SET ValueBased = FALSE;
ALTER TABLE luminex.GuideSet ALTER COLUMN ValueBased SET NOT NULL;

ALTER TABLE luminex.GuideSet ADD COLUMN EC504PLAverage REAL;
ALTER TABLE luminex.GuideSet ADD COLUMN EC504PLStdDev REAL;
ALTER TABLE luminex.GuideSet ADD COLUMN EC505PLAverage REAL;
ALTER TABLE luminex.GuideSet ADD COLUMN EC505PLStdDev REAL;
ALTER TABLE luminex.GuideSet ADD COLUMN AUCAverage REAL;
ALTER TABLE luminex.GuideSet ADD COLUMN AUCStdDev REAL;
ALTER TABLE luminex.GuideSet ADD COLUMN MaxFIAverage REAL;
ALTER TABLE luminex.GuideSet ADD COLUMN MaxFIStdDev REAL;